const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const { buildReport } = require('../utils/reportData');

const logoPath = path.join(__dirname, '..', 'utils', 'logo.png');

const toCellText = (value) => {
  if (value === null || value === undefined) return '';
  if (value instanceof Date) return value.toLocaleString('en-GB');
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value).replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g, '');
};

const getColumnText = (row, column, index) => {
  if (Array.isArray(row)) return toCellText(row[index]);
  return toCellText(row?.[column.key]);
};

const safeFilename = (value) => value
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/^-|-$/g, '') || 'admin-report';

exports.generatePdf = async (req, res) => {
  try {
    const { documentName, rows, columns, summary } = await buildReport(req.body || {});
    const layout = columns.length > 4 ? 'landscape' : 'portrait';
    const doc = new PDFDocument({ size: 'A4', layout, margin: 36 });
    const filename = `${safeFilename(documentName)}.pdf`;
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.setHeader('X-Report-Row-Count', String(rows.length));
    res.setHeader('X-Report-Truncated', String(rows.length === 2000));
    const pdfChunks = [];
    doc.on('data', (chunk) => pdfChunks.push(chunk));
    doc.on('end', () => {
      const pdf = Buffer.concat(pdfChunks);
      res.setHeader('Content-Length', String(pdf.length));
      res.end(pdf);
    });
    doc.on('error', (error) => {
      if (res.headersSent) return res.destroy(error);
      return res.status(500).json({ success: false, message: 'Failed to render the report PDF.' });
    });

    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;
    const left = 36;
    const right = pageWidth - 36;
    const tableWidth = right - left;
    const columnWidth = tableWidth / columns.length;
    const colors = {
      ink: '#202b2a',
      brand: '#1769aa',
      soft: '#edf4f8',
      grid: '#cbd7df',
      muted: '#5f6d75',
      white: '#ffffff'
    };
    let pageNumber = 1;

    const drawFooter = () => {
      doc.save();
      doc.font('Helvetica').fontSize(8).fillColor(colors.muted);
      const footerY = pageHeight - 47;
      doc.text('Stay In Hostel  |  Admin Report', left, footerY, { lineBreak: false });
      doc.text(`Page ${pageNumber}`, right - 70, footerY, { width: 70, align: 'right', lineBreak: false });
      doc.restore();
    };

    const drawTableHeader = (top) => {
      const headerHeight = 24;
      columns.forEach((column, index) => {
        const x = left + index * columnWidth;
        doc.rect(x, top, columnWidth, headerHeight).fillAndStroke(colors.brand, colors.brand);
        doc.font('Helvetica-Bold').fontSize(8).fillColor(colors.white)
          .text(column.label, x + 5, top + 7, { width: columnWidth - 10, height: headerHeight - 8, ellipsis: true });
      });
      return top + headerHeight;
    };

    const drawContinuationHeader = () => {
      doc.font('Helvetica-Bold').fontSize(12).fillColor(colors.brand)
        .text(`${documentName} - continued`, left, 30, { lineBreak: false });
      doc.font('Helvetica').fontSize(8).fillColor(colors.muted)
        .text(summary, left, 49, { width: tableWidth, lineBreak: false, ellipsis: true });
      return drawTableHeader(68);
    };

    const generatedOn = new Date().toLocaleDateString('en-US', {
      weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
    });
    const generatedByName = [req.user.firstName, req.user.lastName].filter(Boolean).join(' ') || 'Admin';
    const generatedBy = `${generatedByName} (${req.user.email || ''})`;
    const headingX = left + 64;
    const headingWidth = tableWidth - 64;

    if (fs.existsSync(logoPath)) doc.image(logoPath, left, 26, { fit: [54, 54] });
    doc.font('Helvetica-Bold').fontSize(22).fillColor(colors.brand)
      .text('Stay In Hostel', headingX, 27, { width: headingWidth, align: 'center', lineBreak: false });
    doc.font('Helvetica').fontSize(11).fillColor(colors.ink)
      .text('Admin Panel', headingX, 55, { width: headingWidth, align: 'center', lineBreak: false });
    doc.font('Helvetica-Bold').fontSize(12).fillColor(colors.ink)
      .text(documentName, headingX, 76, { width: headingWidth, align: 'center', lineBreak: false, ellipsis: true });

    doc.font('Helvetica').fontSize(8).fillColor(colors.ink)
      .text(`Generated on: ${generatedOn}`, left, 108, { width: tableWidth * 0.48, lineBreak: false });
    doc.text(`Generated by: ${generatedBy}`, left + tableWidth * 0.48, 108, {
      width: tableWidth * 0.52, align: 'right', lineBreak: false, ellipsis: true
    });
    doc.fillColor(colors.muted).text(summary, left, 126, { width: tableWidth, lineBreak: false, ellipsis: true });

    let cursorY = drawTableHeader(148);
    const fontSize = Math.max(6, Math.min(8, 78 / columns.length));

    if (rows.length === 0) {
      doc.rect(left, cursorY, tableWidth, 30).fillAndStroke(colors.white, colors.grid);
      doc.font('Helvetica').fontSize(9).fillColor(colors.muted)
        .text('No records match the selected filters.', left + 8, cursorY + 10, { width: tableWidth - 16 });
      cursorY += 30;
    }

    rows.forEach((row, rowIndex) => {
      const cells = columns.map((column, index) => getColumnText(row, column, index));
      const cellHeights = cells.map((text) => doc.font('Helvetica').fontSize(fontSize)
        .heightOfString(text || ' ', { width: Math.max(8, columnWidth - 10), lineGap: 1 }));
      const rowHeight = Math.max(22, ...cellHeights.map((height) => height + 9));

      if (cursorY + rowHeight > pageHeight - 42) {
        drawFooter();
        doc.addPage({ size: 'A4', layout, margin: 36 });
        pageNumber += 1;
        cursorY = drawContinuationHeader();
      }

      cells.forEach((cellText, index) => {
        const x = left + index * columnWidth;
        const fill = rowIndex % 2 === 0 ? colors.white : colors.soft;
        doc.rect(x, cursorY, columnWidth, rowHeight).fillAndStroke(fill, colors.grid);
        doc.font('Helvetica').fontSize(fontSize).fillColor(colors.ink)
          .text(cellText, x + 5, cursorY + 5, { width: columnWidth - 10, height: rowHeight - 8, lineGap: 1 });
      });
      cursorY += rowHeight;
    });

    drawFooter();
    doc.end();
  } catch (error) {
    if (res.headersSent) return res.destroy(error);
    const status = error.statusCode || 500;
    return res.status(status).json({
      success: false,
      message: status === 400 ? error.message : 'Failed to generate the requested report.'
    });
  }
};